name: Build and Push Docker Compose

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Push Docker Compose
      run: |
        docker-compose build
        docker-compose push

