name: Deploy using on Docker Compose EC2 AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Docker to AWS (EC2)
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.4.6
      with:
        aws_access_key_id: AKIAUYV375ELC3UUR4X3
        aws_secret_access_key: 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
