name: Deploy using on Docker Compose EC2 AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
            - name: Deploy Docker to AWS (EC2)
                  # You may pin to the exact commit or the version.
                  # uses: bitovi/github-actions-deploy-docker-to-ec2@872d733d9981dbb58302746dd53d000efad616bd
                  uses: bitovi/github-actions-deploy-docker-to-ec2@v0.4.6
                          with:
                            # AWS access key ID
                            aws_access_key_id: AKIAUYV375ELC3UUR4X3
                            # AWS secret access key
                            aws_secret_access_key: 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
                            # AWS session token
